### PR TITLE
Img explore

### PR DESCRIPTION
**Pull request by conig**
Adds a list of exploratory images.

### CODE REVIEW

**Comment by conig** [comment]
Hold off merging this one. It's too slow, will convert images to jpg and put them in a report rather than save a list of gg objects.

**Comment by conig** [comment]
I think this is ready now. I didn't end up making a report, but did save to a folder. saving gg objects is leagues faster than caching.

**Comment by mnoetel** [comment]
Want to fix these conflicts mate?

**Comment by conig** [comment]
@mnoetel thanks done

**Pull request merged**
